#!/usr/bin/env bash
# Phase 4 dependency bring-up for the real ECHO local-AI stack (Linux/macOS).
# Mirror of scripts/setup_deps.ps1 — see that file's header for the full rationale.
#
# Automates what can be automated (whisper.cpp + llama.cpp build, free models);
# prints manual steps for OpenCV/SDL2, the Piper binary, the LLM gguf, and the
# account-gated Porcupine key + custom "Hey ECHO" wake word.
#
# Usage: scripts/setup_deps.sh [--prefix DIR] [--llama-gguf-url URL]
#                              [--skip-build] [--skip-models]
set -euo pipefail

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tp="$repo/third_party"; models="$repo/models"
prefix="$tp/install"; llama_url=""; skip_build=0; skip_models=0

while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) prefix="$2"; shift 2;;
    --llama-gguf-url) llama_url="$2"; shift 2;;
    --skip-build) skip_build=1; shift;;
    --skip-models) skip_models=1; shift;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done
mkdir -p "$tp" "$models"

info() { printf '\033[36m[setup] %s\033[0m\n' "$*"; }
warn() { printf '\033[33m[setup] %s\033[0m\n' "$*"; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "Required tool '$1' not found on PATH."; exit 1; }; }
need git; need cmake

build_cmake() { # name url
  local name="$1" url="$2" src="$tp/$1"
  [ -d "$src" ] || { info "cloning $name ..."; git clone --depth 1 "$url" "$src" >/dev/null; }
  info "building $name ..."
  cmake -S "$src" -B "$src/build" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
  cmake --build "$src/build" -j
  cmake --install "$src/build" --prefix "$prefix"
  git -C "$src" rev-parse --short HEAD
}

whisper_commit="(skipped)"; llama_commit="(skipped)"
if [ "$skip_build" -eq 0 ]; then
  whisper_commit="$(build_cmake whisper.cpp https://github.com/ggml-org/whisper.cpp.git)"
  llama_commit="$(build_cmake llama.cpp https://github.com/ggml-org/llama.cpp.git)"
  info "whisper.cpp @ $whisper_commit, llama.cpp @ $llama_commit -> $prefix"
else
  warn "--skip-build: not building whisper.cpp / llama.cpp"
fi

fetch() { # url dest
  [ -f "$2" ] && { info "have $(basename "$2") already"; return; }
  info "downloading $(basename "$2") ..."
  curl -fL "$1" -o "$2" || warn "could not fetch $1 -> get it manually into $2"
}
if [ "$skip_models" -eq 0 ]; then
  fetch "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-base.en-q5_1.bin" "$models/ggml-base.en-q5_1.bin"
  fetch "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx" "$models/en_US-amy-medium.onnx"
  fetch "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx.json" "$models/en_US-amy-medium.onnx.json"
  fetch "https://github.com/opencv/opencv_zoo/raw/main/models/face_detection_yunet/face_detection_yunet_2023mar.onnx" "$models/face_detection_yunet.onnx"
  fetch "https://github.com/opencv/opencv_zoo/raw/main/models/face_recognition_sface/face_recognition_sface_2021dec.onnx" "$models/face_recognition_sface.onnx"
  [ -n "$llama_url" ] && fetch "$llama_url" "$models/llm.gguf"
else
  warn "--skip-models: not downloading models"
fi

cat > "$models/INSTALLED_VERSIONS.md" <<EOF
# ECHO OS — installed dependency versions (Phase 4 bring-up)

Generated by \`scripts/setup_deps.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).
Fill in the rows this script can't detect (OpenCV, SDL2, Piper, Porcupine) by hand.

| Dependency  | Version / commit          | How installed                 |
|-------------|---------------------------|-------------------------------|
| Toolchain   | $(cc --version 2>/dev/null | head -1 || echo n/a) | system |
| CMake       | $(cmake --version | head -1) | on PATH |
| whisper.cpp | $whisper_commit | built from source -> $prefix |
| llama.cpp   | $llama_commit | built from source -> $prefix |
| OpenCV      | _fill in_                 | _pkg manager_ |
| SDL2        | _fill in_                 | _pkg manager_ |
| SDL2_ttf    | _fill in_                 | _pkg manager_ |
| Piper       | _fill in_ (release tag)   | _binary_ |
| Porcupine   | _fill in_ (SDK version)   | _Picovoice console + SDK_ |
| LLM gguf    | _fill in_ (model + quant) | _model card_ |
EOF
info "wrote $models/INSTALLED_VERSIONS.md"

cat <<'EOF'

==================== MANUAL STEPS STILL REQUIRED ====================
1. OpenCV + SDL2 + SDL2_ttf via your package manager, e.g.:
     apt:  sudo apt install libopencv-dev libsdl2-dev libsdl2-ttf-dev
     brew: brew install opencv sdl2 sdl2_ttf
2. Piper binary: download from https://github.com/rhasspy/piper/releases
   (put `piper` on PATH or set ECHO_PIPER_BIN).
3. LLM .gguf (e.g. Llama-3.2-3B-Instruct Q4_K_M) -> models/llm.gguf
   (or re-run with --llama-gguf-url "<direct url>").
4. Porcupine (account-gated — only you can do this):
   AccessKey + custom "Hey ECHO" .ppn from https://console.picovoice.ai ->
     models/hey-echo.ppn, models/porcupine_params.pv, models/porcupine_access_key.txt
5. Enrolled faces: models/faces/<name>.jpg (one clear photo per person).

Then build with everything ON:
     cmake -S . -B build-real -DECHO_REAL_AI=ON -DCMAKE_PREFIX_PATH="$prefix" \
           -DPORCUPINE_ROOT=<sdk> [-DECHO_LLAMA_KV_CLEAR=self|cache]
     cmake --build build-real -j
Record OpenCV/SDL2/Piper/Porcupine/LLM versions in models/INSTALLED_VERSIONS.md.
EOF
